### PR TITLE
Bypass google oauth in development mode

### PR DESCRIPTION
**Pull request by GaneshSPatil**
* Do not provide the authentication **APP_ID** and **APP_SECRET** at the time of starting development server
* No need of specifying **TWEETABLE_ADMIN_EMAIL** in development mode
* In development mode, a dummy admin user will be present on server start up.

### CODE REVIEW

**Comment by GaneshSPatil** [comment]
One of the problems with the current approach is that it requires `rake db:seed` to be executed before starting the development server. 
As there is no way to get the db connection pool at the time of development server configuration.

And i think it should be OK.

**Comment by blpabhishek** [comment]
For this problem, I was of the opinion to have a mock auth server in place which gives you a valid response to all the auth calls.

**Comment by GaneshSPatil** [comment]
@blpabhishek -- I do agree with you on having different flows based on the Deployment mode is a bad idea.
Though, the efforts required to create a mock OAuth Server was just too much than bypassing the authentication for development mode.
If we mock the OAuth server for the development mode, it will still require us to pass the OAuth tokens (AppId, AppSecret) and user information(TWEETABLE_ADMIN_USER). I found it unnecessary, as the functionality of the application will still be same for real user and mocked user. We really ain't losing anything by bypassing the auth in development mode.

Thoughts? Ideas?

**Comment by blpabhishek** [comment]
The proposed solution works we can use this, but I guess we should definitely give try to mocking the client. We are using a library "omniauth" which already has some method of mocking the auth behaviour.  

https://github.com/omniauth/omniauth/wiki/Integration-Testing

**Comment by GaneshSPatil** [comment]
@blpabhishek -- Thanks for the link. I will give it a try soon and get back to you on this.

**Pull request merged**
